# Generated by Django 5.0.6 on 2024-05-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderitem_precio_alter_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
